### ISSUE TITLE
ModuleNotFoundError 'keras.engine.base_layer'

### ISSUE THREAD

**Issue by Wisgon** [lim-anggun/FgSegNet_v2#1]
Hi, thanks for the job!
I follow the instruction to run these project, after I installed the environment, I run "python3 FgSegNet_v2_CDnet.py" but I got some error below:
`Traceback (most recent call last):
  File "FgSegNet_v2_CDnet.py", line 37, in <module>
    from FgSegNet_v2_module import FgSegNet_v2_module
  File "/home/jhd/face_recognition/softwares/FgSegNet_v2/scripts/FgSegNet_v2_module.py", line 15, in <module>
    from my_upsampling_2d import MyUpSampling2D
  File "/home/jhd/face_recognition/softwares/FgSegNet_v2/scripts/my_upsampling_2d.py", line 13, in <module>
    from keras.engine.base_layer import InputSpec
ModuleNotFoundError: No module named 'keras.engine.base_layer'`

Is there something I miss?

**Comment by lim-anggun** [comment]
Hi, this problem occurs because it cannot import `base_layer` module. There should be a file name `base_layer.py` inside `keras/engine` directory. Does this file exist? What version of keras do you use? Do you use Spyder IDE in your training?

**Comment by Wisgon** [comment]
I look into my keras directory, there is no file name base_layer.py,  my version of keras is 2.0.6. But I didn't use Spyder IDE, must I use this IDE so that I can run the code?

**Comment by Wisgon** [comment]
I had solved the problem, I changed the version of keras to 2.2.0, then I run the code successfully.
Thanks for replying.
