### ISSUE TITLE
how to train my own data?

### ISSUE THREAD

**Issue by Tomingz** [lim-anggun/FgSegNet_v2#12]
thanks a lot  for your great work, but how to make my own data like the CDnet2014? and how to train it?

**Comment by lim-anggun** [comment]
Hello @Tomingz. My apologies for the delayed response.

If you want to adapt it to new videos, you need to **fine-tune** FgSegNet with a minimal training set (freeze the weights and fine-tune some layers based on the amount of your training set). Hope this gives you a hint.

(reopen issued as needed)
