### ISSUE TITLE
How can I load model?

### ISSUE THREAD

**Issue by Wisgon** [lim-anggun/FgSegNet_v2#2]
Hi, I had finished training, and I got some *.h5 files. But I'm not familiar with keras, so I use the code like this to load model:
`from keras.models import load_model `
`path = "/path/to/mdl_skating.h5 "`
`model = load_model(path)` 

But it raise "ValueError: Unknow layer: InstanceNormalization"

I haven't used keras before. So can you give me a demo to load "mdl_skating.h5" to predict "/CDNet2014_dataset/badWeather/skating" video sequence?

**Comment by Wisgon** [comment]
Ahha, I found https://github.com/lim-anggun/FgSegNet/blob/master/test_prediction.ipynb
Closing the issue.

**Comment by Wisgon** [comment]
I use `model = load_model(mdl_path, custom_objects={'MyUpSampling2D': MyUpSampling2D})` to load model, but it still raise  "ValueError: Unknow layer: InstanceNormalization"

**Comment by lim-anggun** [comment]
hi @Wisgon,
there is an **InstanceNormalization** file inside the scripts folder. What you need to do is:
1. Copy and paste `instance_normalization.py` into the same folder as Jupyter Notebook
2. load the model as following (I did't test yet, but hope it works):

```
# ... the rest of your code ...
from instance_normalization import InstanceNormalization
model = load_model(mdl_path, custom_objects={'MyUpSampling2D': MyUpSampling2D, 'InstanceNormalization': InstanceNormalization})
```
Let me know if it works.

**Comment by Wisgon** [comment]
It works!
But, I found that I should add something else to make it work:
```
from FgSegNet_v2_module.py import loss2, acc2
model = load_model(mdl_path, custom_objects={'MyUpSampling2D': MyUpSampling2D, 'InstanceNormalization': InstanceNormalization, 'loss2':loss2, 'acc2':acc2})
```
If you don't add loss2 and acc2, it will raise "Unknow loss function: loss2"

**Comment by 124399839** [comment]
@Wisgon 请问你在自己的数据上，该方法表现效果如何？
